import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from './components/Navbar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Musica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/img/Logo.png" />
      </Head>

        <Navbar/>

      </div>
  )
}
