import Head from "next/head";
import styles from "../styles/Home.module.css";
import Navbar from "./components/Navbar";
import Sidebar from "./components/Sidebar";
import Profile from "./components/Profile";
import Hero from "./components/Hero";
import styled from "styled-components";
import { Main } from "next/document";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Musica</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='../public/img/Logo.png' />
      </Head>

      <Navbar />
      <MainSection>
        <SideMenu>
          <Sidebar />
          <Profile />
        </SideMenu>
        <Hero />
      </MainSection>
    </div>
  );
}

const SideMenu = styled.div``;
const MainSection = styled.div`
  display: flex;
`;
